<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.github.jeffnelson</groupId>
        <artifactId>jackson-merge-patch-parent</artifactId>
        <version>2.0.0</version>
    </parent>

    <artifactId>jackson-merge-patch-validations</artifactId>
    <packaging>jar</packaging>

    <name>Jackson Merge Patch Validations</name>
    <description>Validation constraint annotations for PatchField types supporting RFC-7396 merge-patch</description>

    <properties>
        <commons-lang3.version>3.5</commons-lang3.version>
        <validation-api.version>1.1.0.Final</validation-api.version>
        <hibernate-validator.version>5.3.6.Final</hibernate-validator.version>
    </properties>

    <dependencies>
        <!-- Inter-module dependency -->
        <dependency>
            <groupId>com.github.jeffnelson</groupId>
            <artifactId>jackson-merge-patch-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang3.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>${validation-api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>${hibernate-validator.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
    </dependencies>

</project>
